### PR TITLE
extract out logic from load CLI

### PR DESCRIPTION
**Pull request by robinandeer**
This is how I'm thinking about moving logic out of the CLI

It could be much improved but it's moving in the direction of "easier to test" so I think it's a good thing :)

related to #3

### CODE REVIEW

**Comment by robinandeer** [comment]
Hmm.. this worked locally for me :confused: 

```
<Result ServerSelectionTimeoutError('localhost:27017: [Errno 111] Connection refused',)>.exit_code
```

Any idea?

**Comment by robinandeer** [comment]
Would it be any point in just restarting the build on travis? (only you can do this :))

**Comment by moonso** [comment]
Nej failar fortfarande

**Comment by robinandeer** [comment]
aha, but all the builds are failing (also master branch)
https://travis-ci.org/moonso/loqusdb/builds

I'll modify the travis setup file to install mongodb :8ball:

**Comment by robinandeer** [comment]
Yipeeee :cake:

**Comment by moonso** [comment]
Nooo!

**Comment by moonso** [comment]
I'll figure out another way!

**Comment by robinandeer** [comment]
but it works... and you need mongo to run the tests - it's already installed on travis so just need to activate it

**Comment by moonso** [comment]
:+1:

**Pull request merged**
