### PR TITLE
fixed the end_chromosome problem

### PR DESCRIPTION
**Pull request by J35P312**
Now it works!

loqusdb variants -t sv --chromosome 5 --end-chromosome 10

 Find all sv variants {'chrom': '5', 'end_chrom': '10'}
{'_id': ObjectId('5b2057c0e181b325cb7bc536'),
 'chrom': '5',
 'end_chrom': '10',
 'end_left': 68944905,
 'end_right': 68952905,
 'end_sum': 68948905,
 'families': ['b'],
 'length': 100000000000.0,
 'nr_events': 1,
 'pos_left': 39783793,
 'pos_right': 39791793,
 'pos_sum': 39787793,
 'sv_type': 'BND'}

### CODE REVIEW

**Comment by moonso** [comment]
Perfect! Could you add a test to avoid this again?

**Comment by J35P312** [comment]
I will give it a try =P

**Comment by moonso** [comment]
Do or do not. There is no try 
image

**Comment by J35P312** [comment]
Aloha!
Now I Have made a test for interchromosomal variations!

**Pull request merged**
